### ISSUE TITLE
4 errors after ipsw extraction

### ISSUE THREAD

**Issue by JauneXIX** [UnbendableStraw/homepod-restore#3]
Hello,
I have this when I try to restore a 1st Gen HomePod: 

Checking IPSW for required components...
All required components found in IPSW
Extracting filesystem from IPSW: myrootfs.dmg
[==================================================] 100.0%
Getting ApNonce in dfu mode... ad bb 7d 5f dd 61 80 db 40 9e 07 5d 11 f8 46 46 f2 f0 89 6a 
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode... fe 43 8e 38 be f9 bd 5b a0 80 95 07 f8 80 89 48 6f e4 a1 d4 
Received SHSH blobs
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode... fe 43 8e 38 be f9 bd 5b a0 80 95 07 f8 80 89 48 6f e4 a1 d4 
**ERROR: Unable to find UniqueBuildID node
ERROR: Unable to find restore manifest
ERROR: Unable to add common tags to TSS request
ERROR: Unable to get SHSH blobs for this device (Recovery Customer Install)**

Have you any idea about these errors?

Thank you very much.

**Comment by UnbendableStraw** [comment]
Make sure you are using the 18.0 ipsw. The latest version of idevicerestore has a bug with 18.0. You need to uninstall idevicerestore then checkout and install the version before the bug, as follows (one command at a time): 

`brew uninstall d235j/ios-restore-tools/idevicerestore`
`git clone https://github.com/libimobiledevice/idevicerestore.git`
`cd idevicerestore`
`git checkout d2e1c4f`
`./autogen.sh`
`make`
`sudo make install`

**Comment by JauneXIX** [comment]
Thank you for your reply.
I re-did it on a clean macOS install but in the part "p.4" I had to use this comman: "brew install d235j/ios-restore-tools/idevicerestore" before the command: "brew tap d235j/ios-restore-tools".
If I don't do that, idevicerestore doesn't install and the commands: "make" and "sudo make install" doesn't work.

So after that my HomePod was successfully restored.

Thank you, this line you sent "brew uninstall d235j/ios-restore-tools/idevicerestore" helped me a lot :)

**Comment by UnbendableStraw** [comment]
Woohoo!
