### ISSUE TITLE
Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by 15225303865** [UnbendableStraw/homepod-restore#6]
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7000
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7000
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7000
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7000
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
idevicerestore 1.0.0-215-gd2e1c4f (libirecovery 1.2.1, libtatsu 1.0.3)
irecv_event_cb: device 00121d5430b840a6 (udid: N/A) connected in DFU mode
Found device in DFU mode
ECID: 5098797012631718
Identified device as b238aap, AudioAccessory1,1
Device Product Version: N/A
Device Product Build: N/A
Extracting BuildManifest from IPSW
IPSW Product Version: 18.0
IPSW Product Build: 22J357 Major: 22
Device supports Image4: true
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
################################ [ WARNING ] #################################
# You are about to perform an *ERASE* restore. ALL DATA on the target device #
# will be IRREVERSIBLY DESTROYED. If you want to update your device without  #
# erasing the user data, hit CTRL+C now and restart without -e or --erase    #
# command line switch.                                                       #
# If you want to continue with the ERASE, please type YES and press ENTER.   #
##############################################################################
> YES
Checking IPSW for required components...
All required components found in IPSW
Extracting filesystem from IPSW: myrootfs.dmg
[==================================================] 100.0%
Getting ApNonce in dfu mode... e2 10 ec 30 fe d1 d7 47 b0 11 93 2b 4d 45 80 7d 95 d9 15 44 
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode... 1f 7e 07 ce 6d 28 6b 8b 03 ff 09 b6 cf 98 c7 96 9c 31 80 3e 
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
Recv failure: Connection reset by peer
ERROR: TSS request failed: Recv failure: Connection reset by peer (status=-1)
ERROR: Unable to send TSS request
ERROR: Unable to get SHSH blobs for this device
apple@appledeMacBook-Pro idevicerestore %

**Comment by UnbendableStraw** [comment]
This is usually due to using an incompatible version of idevicerestore with the version of .ipsw you are restoring with.

The (latest) idevicerestore we have not yet gotten to work with the way we build the (18.0).ipsw. So you must install an older version of idevicerestore.

brew uninstall d235j/ios-restore-tools/idevicerestore
git clone https://github.com/libimobiledevice/idevicerestore.git 
cd idevicerestore
git checkout d2e1c4f
./autogen.sh
make
sudo make install
