### ISSUE TITLE
Unable to build idevicerestore

### ISSUE THREAD

**Issue by blaaaakuu** [UnbendableStraw/homepod-restore#9]
MacOS 14.6.1 throws `dfu.c:87:2: error: call to undeclared function 'irecv_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]` when running `make`

**Comment by InteractionEngineer** [comment]
Hi, this still happens to me. How did you solve it? I already tried updating to a newer version of `idevicerestore` including a required update of `libtatsu`. But no luck so far.

**Comment by InteractionEngineer** [comment]
@UnbendableStraw How were you able to `make` (build) this project when we are stopped by this error?

**Comment by UnbendableStraw** [comment]
Look at the second bullet point in the [Troubleshooting section! ](https://github.com/UnbendableStraw/homepod-restore?tab=readme-ov-file#troubleshooting)

**Comment by InteractionEngineer** [comment]
@UnbendableStraw Thank you for your quick and clear response. I hope raising this question again is going to help another impatient person like me who skipped this last part of the readme. Obviously it works well now. 😄

**Comment by Charmandrigo** [comment]
I have the same error and idevicerestore isn't even installed
```
Configuration for idevicerestore 1.0.0-215-gd2e1c4f:
-------------------------------------------

  Install prefix: .........: /usr/local

  Now type 'make' to build idevicerestore 1.0.0-215-gd2e1c4f,
  and then 'make install' for installation.

drigo@Rodrigos-Mac-mini idevicerestore % make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
  CC       idevicerestore-dfu.o
dfu.c:87:2: error: call to undeclared function 'irecv_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   87 |         irecv_init();
      |         ^
1 error generated.
make[2]: *** [idevicerestore-dfu.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```
